/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + a cheap store summary, for the frontend's plumbing check.
         *
         *     Run discovery is best-effort: a malformed/absent store must never 500 the
         *     health probe, so discovery failures degrade to ``runs: 0`` rather than
         *     propagating (the broad guard is deliberate and scoped to this probe).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Every discoverable run, newest first by last-written chain mtime.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description One run's metadata, schema, and authoritative verdict.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/mle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mle
         * @description The point estimate + multi-start results of an MLE ('scout') fit. 404 for a
         *     run that isn't an MLE fit, or one whose ``mle_params.toml`` is unreadable.
         */
        get: operations["get_mle_api_runs__run_id__mle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/posterior": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Posterior
         * @description Doc-labelled posterior summary (the forest-plot payload). Params are in
         *     the model's estimated order; a run with no draws yet returns ``params=[]``
         *     and ``n_tail=0`` rather than erroring. ``chains`` restricts to an include-list
         *     of chain ids; the pooled quantiles and R̂/ESS then recompute on the retained
         *     chains (dropping a stuck chain here matches the Pair / Traces / Diagnostics
         *     tabs, which share this selection).
         */
        get: operations["get_posterior_api_runs__run_id__posterior_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/draws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draws
         * @description Row-aligned post-warmup draws (plus marginal prior samples) for the
         *     marginal densities and the pair plot. Pooled across chains, thinned to
         *     ``max_draws``; ``params`` in estimated order. A run with no draws yet returns
         *     empty columns and ``n_draws=0`` (priors are still sampled). ``chains``
         *     restricts the pool to an include-list of chain ids (drop stuck chains).
         */
        get: operations["get_draws_api_runs__run_id__draws_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source
         * @description The fit's sources: the highlighted ``.camdl`` model (the copy archived in
         *     the run leaf when present, else read live from the recorded path) and the
         *     ``fit.toml`` (always archived in the run leaf).
         */
        get: operations["get_source_api_runs__run_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/model-render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Render
         * @description The run's structured model math (``model.render.json``) for the rendered
         *     model view — parameters, definitions, reactions, and ODEs as KaTeX-safe
         *     strings. 404 when the run predates the artifact (the Source tab then shows
         *     only the raw source).
         */
        get: operations["get_model_render_api_runs__run_id__model_render_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/model-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Graph
         * @description The run's compartmental flow graph (``model.graph.json``) for the Model
         *     tab's diagram — base compartments, plates, transition edges (KaTeX rates),
         *     and mean-field couplings. 404 when the run predates the artifact (the Model
         *     tab then shows only the equations / raw source).
         */
        get: operations["get_model_graph_api_runs__run_id__model_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/predictive/{stream}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Predictive
         * @description One stream's posterior-predictive ribbons (``camdl fit predict`` output)
         *     plus the observed series. 404 if the stream has no predictive artifact.
         */
        get: operations["get_predictive_api_runs__run_id__predictive__stream__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/quantity-series/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quantity Series
         * @description One series quantity's banded trajectory (a ribbon). 404 if the run has no
         *     such series quantity in its manifest, or its TSV is missing.
         */
        get: operations["get_quantity_series_api_runs__run_id__quantity_series__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/quantity-scalars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quantity Scalars
         * @description Every scalar quantity, one row per stratum cell — the quantities table.
         *     Manifest-driven (stale orphan TSVs are ignored).
         */
        get: operations["get_quantity_scalars_api_runs__run_id__quantity_scalars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Traces
         * @description Per-parameter, per-chain iteration traces (thinned) for the trace grid.
         *     Includes the estimated coordinates plus any present objective aux columns
         *     (``log_posterior`` / ``log_likelihood``) — the first thing to eyeball for
         *     mixing. ``chains`` restricts to an include-list of chain ids.
         */
        get: operations["get_traces_api_runs__run_id__traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diagnostics
         * @description Convergence diagnostics: camdl's authoritative verdict (findings) and
         *     R̂/ESS where a stage summary exists, else the watcher's live arviz estimate;
         *     plus per-chain mixing (acceptance / trajectory renewal) and the PMMH MAP.
         *     ``chains`` restricts to an include-list of chain ids, so R̂/ESS recompute on
         *     the retained chains once a stuck one is dropped.
         */
        get: operations["get_diagnostics_api_runs__run_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description Prequential model comparison via the authoritative ``camdl compare``.
         *
         *     Resolves each run's ``prequential.json``, shells out (single source of truth
         *     for the elpd / Δelpd math and the evidence scale), and projects the result.
         *     Runs lacking a score artifact are dropped (reported in
         *     ``missing_prequential``). When the surviving models were scored on different
         *     horizons, camdl's commensurability guard trips: Δ columns come back ``None``
         *     and ``commensurable`` is false (the caller may still pass
         *     ``allow_mismatched_horizon`` to acknowledge it explicitly).
         */
        get: operations["compare_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description Every profile-likelihood run under ``profiles/`` — the selector list.
         */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{base_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description One profile-likelihood curve: loglik vs the profiled value, its MLE, and
         *     the 95% CI bracket (interpolated; open on a side the grid doesn't bound).
         */
        get: operations["get_profile_api_profiles__base_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sims
         * @description Every forward-simulation run (``sims/`` tree), newest first.
         */
        get: operations["list_sims_api_sims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sim Series
         * @description One compartment's trajectory across a sim's sweep members. ``state`` picks
         *     the compartment (defaults to the first); columns are resolved once (identical
         *     across members) and summed over strata. ``t_from``/``t_to`` window the axis
         *     (to zoom / cut burn-in) — the series is re-thinned *within* the window so a
         *     zoom keeps full resolution; ``t_min``/``t_max`` report the full domain. A
         *     small sweep ships each thinned member; a large one ships a band + samples.
         */
        get: operations["get_sim_series_api_sims__sim_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Calendar
         * @description The fit's time-axis calendar. A numeric ``time`` value maps to the date
         *     ``origin + time × days_per_unit`` days, so the viewer can render real dates
         *     instead of raw day-indices on every time axis (predictive ribbons, quantity
         *     trajectories). ``None`` on a fit that declares no calendar (relative time —
         *     the axis stays numeric).
         */
        Calendar: {
            /** Origin */
            origin: string;
            /**
             * Time Unit
             * @default days
             */
            time_unit: string;
            /**
             * Days Per Unit
             * @default 1
             */
            days_per_unit: number;
        };
        /**
         * ChainMixing
         * @description Per-chain mixing metric — MH/PMMH acceptance rate or PGAS trajectory
         *     renewal — with an optional healthy band ``(lo, hi)``.
         */
        ChainMixing: {
            /** Label */
            label: string;
            /** Values */
            values: number[];
            /** Band */
            band?: [
                number,
                number
            ] | null;
        };
        /**
         * CompareResponse
         * @description A prequential model comparison. ``commensurable`` is false when the models
         *     were scored on different horizons (``T_score`` mismatch) — Δ columns are then
         *     meaningless and arrive ``None``. ``notes`` carries camdl's advisories (e.g.
         *     the in-sample / plug-in optimism caveat). ``missing_prequential`` lists
         *     requested runs that had no score artifact and were dropped. Rows are in
         *     camdl's order: ascending Δelpd, best-supported last.
         */
        CompareResponse: {
            /** Baseline */
            baseline: string;
            /** Metrics */
            metrics: string[];
            /** Commensurable */
            commensurable: boolean;
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /** Rows */
            rows: components["schemas"]["CompareRow"][];
            /**
             * Missing Prequential
             * @default []
             */
            missing_prequential: string[];
        };
        /**
         * CompareRow
         * @description One model's prequential scores in a comparison, projected from ``camdl
         *     compare --format json``. Δ fields are ``None`` for the baseline row and when
         *     the models are not commensurable (``T_score`` mismatch). ``elpd`` is the
         *     summed out-of-sample log predictive density (higher = better); ``delta_elpd``
         *     is paired against the baseline with ``se_delta_elpd``; ``e_t = exp(Δelpd)`` is
         *     the terminal e-value / Bayes factor; ``evidence_label`` is the Jeffreys tier
         *     of ``delta_elpd_db`` (decibans).
         */
        CompareRow: {
            /** Run Id */
            run_id: string;
            /** Label */
            label: string;
            /** T Score */
            t_score: number;
            /** Elpd */
            elpd: number;
            /** Delta Elpd */
            delta_elpd?: number | null;
            /** Delta Elpd Db */
            delta_elpd_db?: number | null;
            /** Evidence Label */
            evidence_label?: string | null;
            /** E T */
            e_t?: number | null;
            /** Se Delta Elpd */
            se_delta_elpd?: number | null;
            /** Mean Crps */
            mean_crps?: number | null;
            /** Delta Mean Crps */
            delta_mean_crps?: number | null;
            /** Pit Cov90 */
            pit_cov90?: number | null;
            /**
             * Is Baseline
             * @default false
             */
            is_baseline: boolean;
            /**
             * Gap Is Real
             * @default false
             */
            gap_is_real: boolean;
            /**
             * Overconfident
             * @default false
             */
            overconfident: boolean;
        };
        /**
         * DiagnosticsResponse
         * @description The full convergence picture for a run: camdl's verdict (findings), a
         *     per-parameter R̂/ESS table, per-chain mixing, and the PMMH MAP if present.
         *     ``source`` is ``camdl`` when an authoritative stage summary backs R̂/ESS, else
         *     ``live`` (the watcher's arviz estimate while a run is still sampling).
         */
        DiagnosticsResponse: {
            /** Run Id */
            run_id: string;
            /** Warmup Pct */
            warmup_pct: number;
            /** Warmup Cutoff */
            warmup_cutoff: number;
            /** N Tail */
            n_tail: number;
            /** N Chains */
            n_chains: number;
            /**
             * N Chains Warming
             * @default 0
             */
            n_chains_warming: number;
            /** Stage */
            stage?: string | null;
            /** Source */
            source: string;
            /** Logpost Label */
            logpost_label: string;
            /** Findings */
            findings: components["schemas"]["FindingGroup"][];
            /** Params */
            params: components["schemas"]["ParamDiagnostic"][];
            mixing?: components["schemas"]["ChainMixing"] | null;
            /** Map Loglik */
            map_loglik?: number | null;
            /** Map Chain */
            map_chain?: number | null;
            /** Ess Per Iter */
            ess_per_iter?: number | null;
            /** Ess Per Sec */
            ess_per_sec?: number | null;
        };
        /**
         * DimensionInfo
         * @description One indexing dimension and its ordered levels (from the fit's ``schema``).
         */
        DimensionInfo: {
            /** Name */
            name: string;
            /** Levels */
            levels: string[];
        };
        /**
         * DrawsResponse
         * @description Row-aligned post-warmup posterior draws — the substrate for proper
         *     statistical graphics (marginal densities, the pair/corner plot). Row ``i`` is
         *     one joint sample: ``draws[param][i]`` for every param, drawn by chain
         *     ``chain[i]``. Pooled across chains and thinned to at most ``max_draws`` rows;
         *     every value is finite (non-finite rows are dropped to keep alignment).
         */
        DrawsResponse: {
            /** Run Id */
            run_id: string;
            /** Warmup Pct */
            warmup_pct: number;
            /** Warmup Cutoff */
            warmup_cutoff: number;
            /** N Draws */
            n_draws: number;
            /** Params */
            params: string[];
            /**
             * Objectives
             * @default []
             */
            objectives: string[];
            /** Chain */
            chain: number[];
            /** Draws */
            draws: {
                [key: string]: number[];
            };
            /**
             * Prior
             * @default {}
             */
            prior: {
                [key: string]: number[];
            };
            /**
             * Prior Density
             * @default {}
             */
            prior_density: {
                [key: string]: components["schemas"]["PriorCurve"];
            };
        };
        /**
         * FindingGroup
         * @description One ``kind`` of camdl diagnostic finding, collapsed to a single line.
         */
        FindingGroup: {
            /** Kind */
            kind: string;
            /** Severity */
            severity: string;
            /** Headline */
            headline: string;
            /** Params */
            params: string[];
        };
        /**
         * GraphCoupling
         * @description A mean-field coupling: ``edge``'s rate reads the ``aggregate`` pool (its
         *     name, e.g. ``inf_vil``) summed ``over`` the listed plates.
         */
        GraphCoupling: {
            /** Edge */
            edge: string;
            /** Aggregate */
            aggregate: string;
            /**
             * Over
             * @default []
             */
            over: string[];
        };
        /**
         * GraphEdge
         * @description One transition between compartments. ``rate`` is a KaTeX string.
         *     ``source``/``target`` are compartment ids; ``None`` marks an exogenous flow
         *     (``source=None`` → inflow/birth, ``target=None`` → outflow/death), and the
         *     literal ``"c"`` is the compartment iterator (applies to every node — a
         *     plate-family edge such as aging/death). ``advances`` names the plate an edge
         *     steps along (e.g. ``age``), else ``None``. ``reads_pool`` flags a rate that
         *     reads a mean-field aggregate (its couplings carry which pools).
         */
        GraphEdge: {
            /** Id */
            id: string;
            /** From */
            from?: string | null;
            /** To */
            to?: string | null;
            /**
             * Rate
             * @default
             */
            rate: string;
            /** Advances */
            advances?: string | null;
            /**
             * Reads Pool
             * @default false
             */
            reads_pool: boolean;
        };
        /**
         * GraphNode
         * @description One base compartment. ``label`` is a KaTeX string (e.g. ``S_{naive}``);
         *     ``id`` is the plain identifier edges reference.
         */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /**
         * GraphPlate
         * @description One stratifying dimension the compartments are replicated over (e.g.
         *     ``age`` with its ordered ``levels``). Drawn as an enclosing annotation, never
         *     one node per level — a stratified model can be thousands of cells.
         */
        GraphPlate: {
            /** Name */
            name: string;
            /**
             * Levels
             * @default []
             */
            levels: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MleParam
         * @description One coordinate of an MLE fit: the point estimate plus its spread across the
         *     converged restarts (``restart_lo``/``restart_hi`` null when only one restart —
         *     or none — converged). Doc labels (``symbol`` etc.) join in from the model.
         */
        MleParam: {
            /** Name */
            name: string;
            /** Symbol */
            symbol?: string | null;
            /** Description */
            description?: string | null;
            /** Reference */
            reference?: string | null;
            /** Bounds */
            bounds?: [
                number,
                number
            ] | null;
            /** Value */
            value: number | null;
            /** Restart Lo */
            restart_lo?: number | null;
            /** Restart Hi */
            restart_hi?: number | null;
        };
        /**
         * MleResponse
         * @description An MLE ('scout') fit: the point estimate θ̂ (``params``, estimated order),
         *     the optimum ``loglik``, and the multi-start ``restarts`` — the MLE analogue of
         *     convergence diagnostics (how many restarts found the mode vs failed).
         */
        MleResponse: {
            /** Run Id */
            run_id: string;
            /** Label */
            label: string;
            /** Algorithm */
            algorithm: string;
            /** Backend */
            backend: string;
            /** Loglik */
            loglik?: number | null;
            /** N Restarts */
            n_restarts: number;
            /** N Converged */
            n_converged: number;
            /** Params */
            params: components["schemas"]["MleParam"][];
            /** Restarts */
            restarts: components["schemas"]["MleRestart"][];
        };
        /**
         * MleRestart
         * @description One multi-start restart's optimum: its log-likelihood (a huge-negative
         *     sentinel if it failed), the optimizer exit status, and evals spent.
         */
        MleRestart: {
            /** Chain */
            chain: number;
            /** Loglik */
            loglik: number;
            /** Status */
            status: string;
            /** N Evals */
            n_evals: number;
        };
        /**
         * ModelGraph
         * @description The compartmental flow graph (``model.graph.json``) for the Model tab's
         *     diagram. Optional sections default to empty so the contract stays
         *     forward-compatible.
         */
        ModelGraph: {
            /** Model */
            model: string;
            /**
             * Nodes
             * @default []
             */
            nodes: components["schemas"]["GraphNode"][];
            /**
             * Plates
             * @default []
             */
            plates: components["schemas"]["GraphPlate"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["GraphEdge"][];
            /**
             * Couplings
             * @default []
             */
            couplings: components["schemas"]["GraphCoupling"][];
        };
        /**
         * ModelRender
         * @description Structured model math for display (``model.render.json``). Every math
         *     string is KaTeX-safe; the viewer renders leaves and lays them out. Present
         *     for any run (fit or sim). Optional sections default to empty so the contract
         *     stays forward-compatible.
         */
        ModelRender: {
            /** Model */
            model: string;
            /** Mode */
            mode: string;
            /**
             * States
             * @default []
             */
            states: string[];
            /**
             * Dimensions
             * @default []
             */
            dimensions: components["schemas"]["RenderDimension"][];
            /**
             * Parameters
             * @default []
             */
            parameters: components["schemas"]["RenderParameter"][];
            /**
             * Definitions
             * @default []
             */
            definitions: components["schemas"]["RenderDefinition"][];
            /**
             * Transitions
             * @default []
             */
            transitions: components["schemas"]["RenderTransition"][];
            /**
             * Dynamics
             * @default []
             */
            dynamics: components["schemas"]["RenderDynamic"][];
        };
        /**
         * ObservedPoint
         * @description One observed value to overlay (``value`` is null where the series has a hole).
         */
        ObservedPoint: {
            /** Time */
            time: number;
            /**
             * Stratum
             * @default {}
             */
            stratum: {
                [key: string]: string;
            };
            /** Value */
            value?: number | null;
        };
        /**
         * ParamDiagnostic
         * @description One parameter's convergence/precision diagnostics. R̂ and combined ESS are
         *     camdl-authoritative when a stage summary exists, else the live arviz estimate;
         *     tail-ESS / MCSE / sep are the live estimate. ``ess_per_chain`` is camdl's
         *     per-chain breakdown (empty when unavailable). None where not estimable.
         */
        ParamDiagnostic: {
            /** Name */
            name: string;
            /** Symbol */
            symbol?: string | null;
            /** Rhat */
            rhat?: number | null;
            /** Ess Bulk */
            ess_bulk?: number | null;
            /** Ess Tail */
            ess_tail?: number | null;
            /** Mcse */
            mcse?: number | null;
            /** Mean */
            mean: number;
            /** Sd */
            sd: number;
            /** Sep */
            sep?: number | null;
            /**
             * Ess Per Chain
             * @default []
             */
            ess_per_chain: number[];
        };
        /**
         * ParamFamily
         * @description An indexed parameter family — a base name expanded per stratum, e.g.
         *     ``k_raw`` → ``[k_raw_Bo, k_raw_Bombali, …]``. The UI toggles these as a group.
         */
        ParamFamily: {
            /** Base */
            base: string;
            /** Members */
            members: string[];
        };
        /**
         * ParamGroups
         * @description Estimated coordinates partitioned for selection UIs: ungrouped ``scalars``
         *     plus indexed ``families`` (≥2 members). ``default_selection`` is the
         *     recommended visible set (scalars + hyperparameters; family leaves hidden) so
         *     a 20-parameter hierarchical fit doesn't open as a wall of panels.
         */
        ParamGroups: {
            /** Scalars */
            scalars: string[];
            /** Families */
            families: components["schemas"]["ParamFamily"][];
            /** Default Selection */
            default_selection: string[];
        };
        /**
         * ParamPosterior
         * @description One estimated coordinate, doc-labelled and summarized — the unit a forest
         *     plot draws: a point (``q50``) with an interval (``q05``…``q95``), a human
         *     label (``symbol`` / ``description`` / ``reference``), and its prior.
         */
        ParamPosterior: {
            /** Name */
            name: string;
            /** Symbol */
            symbol?: string | null;
            /** Description */
            description?: string | null;
            /** Reference */
            reference?: string | null;
            /** Source */
            source: string;
            /** Prior */
            prior?: string | null;
            /** Bounds */
            bounds?: [
                number,
                number
            ] | null;
            /** Mean */
            mean: number;
            /** Sd */
            sd: number;
            /** Q05 */
            q05: number;
            /** Q25 */
            q25: number;
            /** Q50 */
            q50: number;
            /** Q75 */
            q75: number;
            /** Q95 */
            q95: number;
            /** Rhat */
            rhat?: number | null;
            /** Ess */
            ess?: number | null;
            /**
             * Is Objective
             * @default false
             */
            is_objective: boolean;
        };
        /**
         * ParamTrace
         * @description One parameter's per-chain traces (estimated coordinate, or an objective
         *     like ``log_posterior``).
         */
        ParamTrace: {
            /** Param */
            param: string;
            /** Series */
            series: components["schemas"]["TraceSeries"][];
        };
        /**
         * PosteriorResponse
         * @description Doc-labelled posterior summary for one run — what the first frontend
         *     screen (the forest plot) consumes. ``params`` is in the model's estimated
         *     order; empty when the run has no draws yet.
         */
        PosteriorResponse: {
            /** Run Id */
            run_id: string;
            /** Warmup Pct */
            warmup_pct: number;
            /** Warmup Cutoff */
            warmup_cutoff: number;
            /** N Tail */
            n_tail: number;
            /** Params */
            params: components["schemas"]["ParamPosterior"][];
        };
        /**
         * PredictivePoint
         * @description One posterior-predictive ribbon point: quantiles at a time × stratum, for
         *     a given ``scenario`` × forecast ``horizon`` × ``treatment``. ``scenario`` is
         *     ``as_fitted`` for a scenario-less predict (and for the in-sample one_step
         *     rows, which are scenario-independent).
         */
        PredictivePoint: {
            /** Time */
            time: number;
            /**
             * Stratum
             * @default {}
             */
            stratum: {
                [key: string]: string;
            };
            /**
             * Scenario
             * @default as_fitted
             */
            scenario: string;
            /**
             * Horizon
             * @default
             */
            horizon: string;
            /**
             * Treatment
             * @default
             */
            treatment: string;
            /** Q05 */
            q05: number;
            /** Q25 */
            q25: number;
            /** Q50 */
            q50: number;
            /** Q75 */
            q75: number;
            /** Q95 */
            q95: number;
        };
        /**
         * PredictiveResponse
         * @description One stream's posterior-predictive ribbons + observed series. The frontend
         *     facets by ``stratum`` and filters by ``horizon`` (e.g. free_forward). Time is
         *     dated via the fit-level ``RunDetail.calendar``.
         */
        PredictiveResponse: {
            /** Run Id */
            run_id: string;
            /** Stream */
            stream: string;
            /** Index Dims */
            index_dims: string[];
            /** Scenarios */
            scenarios: string[];
            /** Horizons */
            horizons: string[];
            /** Treatments */
            treatments: string[];
            /** Predictive */
            predictive: components["schemas"]["PredictivePoint"][];
            /** Observed */
            observed: components["schemas"]["ObservedPoint"][];
        };
        /**
         * PriorCurve
         * @description A smooth analytic prior density: ``y`` evaluated at grid ``x`` (same length).
         */
        PriorCurve: {
            /** X */
            x: number[];
            /** Y */
            y: number[];
        };
        /**
         * ProfilePoint
         * @description One grid cell of a profile: the profiled ``coords`` (one value per param —
         *     length 1 for a curve, 2 for a surface) and the best optimized log-likelihood
         *     there (max over restarts). ``nuisance`` is the conditional MLE of the *other*
         *     params at this cell (optimized with the profiled coords held fixed); empty
         *     when the run wrote no per-cell parameter file.
         */
        ProfilePoint: {
            /** Coords */
            coords: number[];
            /** Loglik */
            loglik: number;
            /** N Starts */
            n_starts: number;
            /**
             * Nuisance
             * @default {}
             */
            nuisance: {
                [key: string]: number;
            };
        };
        /**
         * ProfileResponse
         * @description A profile likelihood over one param (a curve) or two (a surface).
         *     ``params`` gives the profiled names and fixes the dimensionality; each
         *     ``points`` cell carries ``coords`` of that length. The MLE is the argmax
         *     cell. ``ci_drop`` is the loglik drop for the 95% confidence set (½·χ²_df:
         *     1.92 for a CI, 3.00 for a 2D region). ``ci_lo``/``ci_hi`` are the 1D CI
         *     bracket (interpolated at the crossings, ``None`` on an unbracketed side, and
         *     always ``None`` for a 2D surface — a region, not an interval).
         */
        ProfileResponse: {
            /** Base Id */
            base_id: string;
            /** Label */
            label: string;
            /** Params */
            params: string[];
            /** Method */
            method: string;
            /** Loglik Type */
            loglik_type: string;
            /** Points */
            points: components["schemas"]["ProfilePoint"][];
            /** Mle Coords */
            mle_coords: number[];
            /** Mle Loglik */
            mle_loglik: number;
            /** Ci Level */
            ci_level: number;
            /** Ci Drop */
            ci_drop: number;
            /** Ci Lo */
            ci_lo?: number | null;
            /** Ci Hi */
            ci_hi?: number | null;
        };
        /**
         * ProfileSummary
         * @description One profile in the selector list: the inference problem and the
         *     parameter(s) it profiles (1 → a curve, 2 → a likelihood surface), plus its
         *     MLE cell — enough to identify and label without the full grid.
         */
        ProfileSummary: {
            /** Base Id */
            base_id: string;
            /** Label */
            label: string;
            /** Params */
            params: string[];
            /** Method */
            method: string;
            /** N Points */
            n_points: number;
            /** Mle Coords */
            mle_coords: number[];
        };
        /**
         * ProgressInfo
         * @description camdl's per-run progress heartbeat (``progress.json``). ``phase`` /
         *     ``step`` / ``total`` are present only while running; ``reason`` only on
         *     failure; ``pct`` is the derived completion fraction (0–100) when step/total
         *     are known. ``updated_at`` is unix seconds — its freshness is the liveness
         *     signal.
         */
        ProgressInfo: {
            /** State */
            state: string;
            /** Phase */
            phase?: string | null;
            /** Step */
            step?: number | null;
            /** Total */
            total?: number | null;
            /** Pct */
            pct?: number | null;
            /** Reason */
            reason?: string | null;
            /** Updated At */
            updated_at?: number | null;
        };
        /**
         * QuantityBandPoint
         * @description One banded snapshot of a series quantity at a scenario × time × stratum.
         *     ``scenario`` is ``as_fitted`` for an old (scenario-less) sidecar.
         */
        QuantityBandPoint: {
            /**
             * Scenario
             * @default as_fitted
             */
            scenario: string;
            /** Time */
            time: number;
            /**
             * Stratum
             * @default {}
             */
            stratum: {
                [key: string]: string;
            };
            /** Q05 */
            q05: number;
            /** Q25 */
            q25: number;
            /** Q50 */
            q50: number;
            /** Q75 */
            q75: number;
            /** Q95 */
            q95: number;
        };
        /**
         * QuantityInfo
         * @description A generated quantity's identity + shape, from the manifest — enough to
         *     decide its rendering (``series`` → ribbon, ``scalar`` → table row) without
         *     reading its TSV. ``censorable`` flags a scalar whose reduction can fail to
         *     fire (a time-to-event), whose band is conditional on firing. ``unit`` is
         *     reserved upstream but currently always null.
         */
        QuantityInfo: {
            /** Name */
            name: string;
            /** Shape */
            shape: string;
            /** Source */
            source: string;
            /** Index Dims */
            index_dims: string[];
            /** Reduce */
            reduce?: string | null;
            /** Unit */
            unit?: string | null;
            /**
             * Censorable
             * @default false
             */
            censorable: boolean;
            /** Symbol */
            symbol?: string | null;
            /** Description */
            description?: string | null;
            /** Reference */
            reference?: string | null;
        };
        /**
         * QuantityScalarRow
         * @description One banded scalar quantity (one row per scenario × stratum cell). A
         *     censorable scalar carries ``p_censored`` (fraction of draws where the event
         *     never fired); a fully-censored cell has ``q* = None`` (no band, only the
         *     count). ``scenario`` is ``as_fitted`` for an old (scenario-less) sidecar.
         */
        QuantityScalarRow: {
            /** Name */
            name: string;
            /**
             * Scenario
             * @default as_fitted
             */
            scenario: string;
            /** Reduce */
            reduce?: string | null;
            /** Source */
            source: string;
            /**
             * Stratum
             * @default {}
             */
            stratum: {
                [key: string]: string;
            };
            /** N Draws */
            n_draws: number;
            /** P Censored */
            p_censored?: number | null;
            /** Q05 */
            q05?: number | null;
            /** Q25 */
            q25?: number | null;
            /** Q50 */
            q50?: number | null;
            /** Q75 */
            q75?: number | null;
            /** Q95 */
            q95?: number | null;
        };
        /**
         * QuantityScalarsResponse
         * @description Every scalar quantity, one row per scenario × stratum cell — the
         *     quantities table. ``scenarios`` is the distinct scenario set (``[]`` when the
         *     fit has no scenario axis).
         */
        QuantityScalarsResponse: {
            /** Run Id */
            run_id: string;
            /** Scenarios */
            scenarios: string[];
            /** Rows */
            rows: components["schemas"]["QuantityScalarRow"][];
        };
        /**
         * QuantitySeriesResponse
         * @description A series quantity's banded trajectory — the ribbon payload. Faceted by
         *     ``stratum`` and overlaid by ``scenario`` on the frontend.
         */
        QuantitySeriesResponse: {
            /** Run Id */
            run_id: string;
            /** Name */
            name: string;
            /** Index Dims */
            index_dims: string[];
            /** Scenarios */
            scenarios: string[];
            /** Points */
            points: components["schemas"]["QuantityBandPoint"][];
        };
        /**
         * RenderDefinition
         * @description A named auxiliary definition, ``tex`` a full KaTeX expression
         *     (e.g. ``N = S + I + R``).
         */
        RenderDefinition: {
            /** Name */
            name: string;
            /** Tex */
            tex: string;
        };
        /**
         * RenderDimension
         * @description One indexing dimension of the model and its ordered levels.
         */
        RenderDimension: {
            /** Name */
            name: string;
            /**
             * Levels
             * @default []
             */
            levels: string[];
        };
        /**
         * RenderDynamic
         * @description One state's ODE, ``tex`` the full KaTeX expression
         *     (e.g. ``\dot{S} = -\frac{\beta S I}{N}``).
         */
        RenderDynamic: {
            /** State */
            state: string;
            /** Tex */
            tex: string;
        };
        /**
         * RenderParameter
         * @description A model parameter for the glossary: ``symbol`` is KaTeX (e.g. ``\beta``);
         *     ``description`` is prose.
         */
        RenderParameter: {
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
            /** Description */
            description?: string | null;
        };
        /**
         * RenderTransition
         * @description One reaction, kept split so the viewer chooses table vs inline-arrow:
         *     ``reactants``/``products`` are KaTeX state expressions, ``rate`` the KaTeX
         *     rate law.
         */
        RenderTransition: {
            /** Name */
            name: string;
            /** Reactants */
            reactants: string;
            /** Products */
            products: string;
            /** Rate */
            rate: string;
        };
        /**
         * RunDetail
         * @description A run's metadata, schema, and verdict — everything but the draws.
         */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Label */
            label: string;
            /** Model */
            model: string;
            /** Algorithm */
            algorithm: string;
            /** Backend */
            backend: string;
            /** Status */
            status: string;
            /**
             * Fit Kind
             * @default posterior
             */
            fit_kind: string;
            /** N Chains */
            n_chains: number;
            /** Max Iter */
            max_iter?: number | null;
            /** Target Sweeps */
            target_sweeps?: number | null;
            /** Estimated */
            estimated: string[];
            groups: components["schemas"]["ParamGroups"];
            /** Streams */
            streams: components["schemas"]["StreamInfo"][];
            /** Dimensions */
            dimensions: components["schemas"]["DimensionInfo"][];
            /** Findings */
            findings: components["schemas"]["FindingGroup"][];
            /** Available Streams */
            available_streams: string[];
            /**
             * Available Quantities
             * @default []
             */
            available_quantities: components["schemas"]["QuantityInfo"][];
            /**
             * Quantity Scenarios
             * @default []
             */
            quantity_scenarios: string[];
            calendar?: components["schemas"]["Calendar"] | null;
            /**
             * Has Model Render
             * @default false
             */
            has_model_render: boolean;
            /**
             * Has Model Graph
             * @default false
             */
            has_model_graph: boolean;
        };
        /**
         * RunSummary
         * @description A run as it appears in the selector list — enough to identify, label, and
         *     badge it without fetching its draws.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Label */
            label: string;
            /** Model */
            model: string;
            /** Algorithm */
            algorithm: string;
            /** Backend */
            backend: string;
            /** Status */
            status: string;
            /**
             * Fit Kind
             * @default posterior
             */
            fit_kind: string;
            /** N Chains */
            n_chains: number;
            /** Chain Ids */
            chain_ids: number[];
            /** N Params */
            n_params: number;
            /** Has Docs */
            has_docs: boolean;
            progress?: components["schemas"]["ProgressInfo"] | null;
            /**
             * Has Prequential
             * @default false
             */
            has_prequential: boolean;
            /** Max Iter */
            max_iter?: number | null;
            /** Target Sweeps */
            target_sweeps?: number | null;
            /** Updated At */
            updated_at: number;
        };
        /**
         * SimBandPoint
         * @description A quantile snapshot across the sweep members at one time — the ensemble
         *     ribbon for a large sweep.
         */
        SimBandPoint: {
            /** Time */
            time: number;
            /** Q05 */
            q05: number;
            /** Q25 */
            q25: number;
            /** Q50 */
            q50: number;
            /** Q75 */
            q75: number;
            /** Q95 */
            q95: number;
        };
        /**
         * SimMemberSeries
         * @description One sweep member's trajectory of a compartment total: aligned
         *     ``time`` + ``value`` (summed over the compartment's strata), thinned.
         */
        SimMemberSeries: {
            /** Member */
            member: string;
            /** Scenario */
            scenario: string;
            /** Time */
            time: number[];
            /** Value */
            value: number[];
        };
        /**
         * SimSeriesResponse
         * @description A sim's compartment trajectory across its sweep members — the overlay
         *     payload. ``states`` lists the selectable compartments; ``state`` is the one
         *     returned. ``mode`` is ``members`` for a small sweep (each thinned trajectory
         *     in ``members``) or ``band`` for a large one (a quantile-across-members ribbon
         *     in ``band`` + a handful of sample ``members`` to toggle on). ``n_members`` is
         *     the full sweep size the band summarises. ``calendar`` dates the axis when
         *     known (else the axis is numeric model-time in days).
         */
        SimSeriesResponse: {
            /** Sim Id */
            sim_id: string;
            /** Model */
            model: string;
            /** State */
            state: string;
            /** States */
            states: string[];
            /**
             * Mode
             * @default members
             */
            mode: string;
            /** N Members */
            n_members: number;
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["SimMemberSeries"][];
            /**
             * Band
             * @default []
             */
            band: components["schemas"]["SimBandPoint"][];
            calendar?: components["schemas"]["Calendar"] | null;
            /**
             * T Min
             * @default 0
             */
            t_min: number;
            /**
             * T Max
             * @default 0
             */
            t_max: number;
        };
        /**
         * SimSummary
         * @description A discoverable forward-simulation run (``sims/`` tree) for the run list.
         *     ``n_members`` is the sweep size (the overlay members).
         */
        SimSummary: {
            /** Sim Id */
            sim_id: string;
            /** Model */
            model: string;
            /** N Members */
            n_members: number;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: number;
        };
        /**
         * SourceFile
         * @description One source artifact: syntax-highlighted ``html`` to render and raw
         *     ``text`` for the copy button. ``present`` is false when the file couldn't be
         *     read (e.g. the model moved since the fit). ``origin`` records where the bytes
         *     came from: ``leaf`` = archived in the self-contained fit run leaf,
         *     ``live`` = read live from the recorded checkout path.
         */
        SourceFile: {
            /** Path */
            path?: string | null;
            /** Present */
            present: boolean;
            /** Origin */
            origin?: ("leaf" | "live") | null;
            /**
             * Html
             * @default
             */
            html: string;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * SourceResponse
         * @description The fit's sources: the ``.camdl`` model (preferably the copy archived in
         *     the run leaf; older fits fall back to the recorded checkout path) and the
         *     ``fit.toml`` (always archived in the run leaf). ``highlight_css`` is the
         *     Pygments token stylesheet to inject once.
         */
        SourceResponse: {
            /** Run Id */
            run_id: string;
            model: components["schemas"]["SourceFile"];
            /** Model Identity */
            model_identity?: string | null;
            fit_toml: components["schemas"]["SourceFile"];
            /** Highlight Css */
            highlight_css: string;
        };
        /**
         * StreamInfo
         * @description One observation stream's structure (from the fit's ``schema``).
         */
        StreamInfo: {
            /** Name */
            name: string;
            /** Index Dims */
            index_dims: string[];
            /** Value Kind */
            value_kind?: string | null;
            /** Likelihood */
            likelihood?: string | null;
        };
        /**
         * TraceSeries
         * @description One chain's thinned trace for one parameter: aligned ``iters`` + ``values``.
         */
        TraceSeries: {
            /** Chain */
            chain: number;
            /** Iters */
            iters: number[];
            /** Values */
            values: number[];
        };
        /**
         * TracesResponse
         * @description Per-parameter, per-chain iteration traces (thinned) for the trace grid —
         *     the raw mixing view. ``warmup_cutoff`` marks the retained-tail boundary.
         */
        TracesResponse: {
            /** Run Id */
            run_id: string;
            /** Warmup Cutoff */
            warmup_cutoff: number;
            /** Params */
            params: string[];
            /** Traces */
            traces: components["schemas"]["ParamTrace"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mle_api_runs__run_id__mle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_posterior_api_runs__run_id__posterior_get: {
        parameters: {
            query?: {
                warmup_pct?: number;
                chains?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosteriorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draws_api_runs__run_id__draws_get: {
        parameters: {
            query?: {
                warmup_pct?: number;
                max_draws?: number;
                chains?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_runs__run_id__source_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_render_api_runs__run_id__model_render_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRender"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_graph_api_runs__run_id__model_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_predictive_api_runs__run_id__predictive__stream__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                stream: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quantity_series_api_runs__run_id__quantity_series__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuantitySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quantity_scalars_api_runs__run_id__quantity_scalars_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuantityScalarsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_traces_api_runs__run_id__traces_get: {
        parameters: {
            query?: {
                warmup_pct?: number;
                max_points?: number;
                chains?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostics_api_runs__run_id__diagnostics_get: {
        parameters: {
            query?: {
                warmup_pct?: number;
                chains?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_compare_get: {
        parameters: {
            query: {
                /** @description run ids to compare (≥2) */
                runs: string[];
                baseline?: string | null;
                allow_mismatched_horizon?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSummary"][];
                };
            };
        };
    };
    get_profile_api_profiles__base_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sims_api_sims_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimSummary"][];
                };
            };
        };
    };
    get_sim_series_api_sims__sim_id__series_get: {
        parameters: {
            query?: {
                state?: string | null;
                t_from?: number | null;
                t_to?: number | null;
            };
            header?: never;
            path: {
                sim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
